Repository laminas/laminas-math, pull requests merged in 2024-12, with the labels that each got.

#20 PHP 8.4 support added
  composer.json
  composer.lock
Labels: Enhancement

#22 Mark `laminas-math` as Abandoned
  .coveralls.yml
  README.md
  composer.json
  mkdocs.yml
Labels: Documentation

#23 Update docs workflow so that the docs are built correctly.
  .github/workflows/auto-close.yml
  .github/workflows/docs-build.yml
  README.md
  mkdocs.yml
Labels: Bug
